// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdkhfarsofyaofwonkjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indka2hmYXJzb2Z5YW9md29ua2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzI4MjcsImV4cCI6MjA2NjcwODgyN30.mzyTrMPk6isV0Sa2HX4fgnXUCxFF7STZFV8It9D4ljA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);